name: CI Pipeline
on:
- push
- pull_request
env:
  RUST_LOG: info
jobs:
  build:
    runs-on: ubuntu2204
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
      shell: bash
